language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.06
sudo: required
install:
  - sudo apt-get install fonts-ipaexfont-mincho fonts-ipaexfont-gothic fonts-lmodern fonts-junicode texlive-fonts-recommended texlive-fonts-extra
  - bash -xv .travis/install-dist.sh
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
  - opam update
  - opam pin add -y --no-action satysfi .
  - opam install -y --deps-only satysfi
script:
  - make all
  - make -C doc primitives.pdf lang.pdf SATYSFI=../satysfi
