language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.06
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam update
# Issue #46: we temporarily pin jbuilder to avoid problems in 1.0+beta18.
# See https://github.com/ocaml/dune/issues/567 for details.
  - opam pin add -y jbuilder 1.0+beta17
# Issue #46: we temporarily pin camlimages to avoid Graphics-related problems.
# See https://github.com/ocaml/dune/issues/563 for details.
  - opam pin add -y camlimages 4.2.6
  - opam install -y ppx_deriving
  - opam install -y menhir
  - opam install -y core_kernel.v0.10.0
  - opam install -y ctypes
  - opam install -y uutf
  - opam install -y result
  - opam install -y bitv
  - opam install -y batteries
  - opam install -y yojson
  - opam install -y camlimages
  - eval `opam config env`
  - git submodule update -i
script:
  - make all
