language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.06
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam pin add -y otfm custom/otfm
  - opam pin add -y camlpdf custom/camlpdf
  - opam pin add -y --no-action satysfi .
  - opam install -y --deps-only satysfi
script:
  - make all
