name: CI

on:
  [pull_request, push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        ocaml-version:
          - 4.10.1
          - 4.11.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install SATySFi dependencies
        run: |
          opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
          opam update
          opam pin add satysfi.dev . --no-action
          opam depext satysfi --yes --with-doc
          opam install . --deps-only --with-doc

      - name: Build SATySFi
        run: opam exec -- make all
